In [3]:
import tensorflow as tf
# 无需事先声明具体值，数值在运算过程中实时给出
data1 = tf.placeholder(tf.float32)
data2 = tf.placeholder(tf.float32)
dataAdd = tf.add(data1, data2)
with tf.Session() as sess:
    print(sess.run(dataAdd, feed_dict={data1:6, data2:2}))
    # 1 dataAdd 2 data (feed_dict = {first parameter:value1, second parameter:value2})
print('end!')

8.0
end!


In [9]:
# 矩阵初始化 [] , []内部：一个[]代表一行（以,分隔），[]里的数据代表列（以,分隔）
import tensorflow as tf
data1 = tf.constant([[6,6]])
data2 = tf.constant([[2],
                     [2]])
data3 = tf.constant([[1,2],
                     [3,4],
                     [5,6]])
print(data3.shape) # 维度
with tf.Session() as sess:
    print(sess.run(data3)) # 打印整体
    print(sess.run(data3[0])) # 打印某一行（下标从0开始）
    print(sess.run(data3[:,0])) # 打印某一列（下标从0开始）
    print(sess.run(data3[0,0])) # 打印某一行某一列对应的元素（下标从0开始）

(3, 2)
[[1 2]
 [3 4]
 [5 6]]
[1 2]
[1 3 5]
1


In [12]:
import tensorflow as tf
mat1 = tf.constant([[2],
                    [3],
                    [4]])
mat2 = tf.zeros_like(mat1) # 产生一个与mat1同维度的全是0的矩阵
mat3 = tf.linspace(0.0, 2.0, 11) # 在0.0-2.0之间生成等间隔的11个数据
mat4 = tf.random_uniform([2,3], -1, 2) # 产生一个(2,3)的矩阵，每个元素在-1-2之间随机取值
with tf.Session() as sess:
    print(sess.run(mat2))
    print(sess.run(mat3))
    print(sess.run(mat4))

[[0]
 [0]
 [0]]
[ 0.          0.2         0.40000001  0.60000002  0.80000001  1.
  1.20000005  1.39999998  1.60000002  1.80000007  2.        ]
[[-0.43213201  0.57048202 -0.73817778]
 [ 0.29105163 -0.2347579   0.14339852]]
